module.exports = {
    client: {
        id: '', 
        token: '',
        secret: '',
        prefix: '>',
        owners: [""],
    },
    database: {
        url: '',
    },
    server: {
        id: '',
        roles: {
            admin: '',
        },
    },
    website: {
        port: 3000, 
        url: 'http://localhost:3000', 
        callback: 'http://localhost:3000/auth/discord/callback', 
        support: '',
        botTags: [ 
            "Fun",
            "NSFW",
            "Game",
            "24-7",
            "Guard",
            "Anime",
            "Music",
            "Memes",
            "Invite",
            "Reddit",
            "Twitch",
            "Crypto",
            "Economy",
            "Logging",
            "Youtube",
            "Utility",
            "General",
            "Leveling",
            "Roleplay",
            "Fortnite",
            "Welcomer",
            "Chat bot",
            "Minecraft",
            "Community",
            "Minigames",
            "Moderation",
            "Protection",
            "Web Dashboard",
            "Reaction Roles",
            "Auto Moderation",
        ],
    },
}